version: '3.8'

services:
  app:
    container_name: app-unicharm-moft
    image: nhan2804/unicharm-moft:v1.0.0
    pull_policy: always
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: 'node dist/main.js'
    ports:
      - 5022:4008
    networks:
      - nesjs-network
    volumes:
      # - ./dist:/var/www/html/dist
      # - ./public:/usr/src/app/public
      - ./.env:/usr/src/app/.env
      # - /etc/hosts:/etc/hosts
      # - /var/www/html/node_modules
    # environment:
    #   - MODE=LIVE
    restart: unless-stopped

networks:
  nesjs-network:
